name: Telegram sender markdownV2 specific
description:  send telegram message in GitHub Markdown
icon: message-circle
inputs:
  bot-token:
    description: 'Telegram Bot Token'
    required: true
  chat-id:
    description: 'Telegram chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true
outputs:
  response:
    description: 'Telegram API response'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bot-token }}
    - ${{ inputs.chat-id }}
    - ${{ inputs.message }}
