name: Telegram sender markdownV2 specific
description: This GitHub Action is a simple Telegram message sender.You can write your message in GitHub Markdown format, and the Action will automatically convert it into Telegram-friendly MarkdownV2 before sending.
icon: message-circle
inputs:
  bot-token:
    description: 'Telegram Bot Token'
    required: true
  chat-id:
    description: 'Telegram chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true
outputs:
  response:
    description: 'Telegram API response'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bot-token }}
    - ${{ inputs.chat-id }}
    - ${{ inputs.message }}
