name: Telegram sender markdownV2 specific
description: This GitHub Action takes any GitHub markdown message and automatically converts it into the MarkdownV2 format supported by Telegram. It allows you to seamlessly send GitHub content—such as issues, pull request updates, or commit messages—directly to your Telegram chats or channels, preserving formatting like bold, italics, links, and code blocks. By integrating this Action into your workflow, you can keep your team updated on repository changes in real-time via Telegram notifications, without manually reformatting messages.
color: blue
icon: message-circle
inputs:
  bot-token:
    description: 'Telegram Bot Token'
    required: true
  chat-id:
    description: 'Telegram chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true
outputs:
  response:
    description: 'Telegram API response'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bot-token }}
    - ${{ inputs.chat-id }}
    - ${{ inputs.message }}
